version: "3.9"

services:
  db:
    image: postgres:14.4-alpine
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:5432"

  app:
    build: ./app
    command: python manage.py runserver localhost:8000
    ports:
        - 8000:8000
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db