version: "3.9"

services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - type: bind
        source: ./db/data/
        target: /var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    ports:
      - "${DB_PORT}:5432"
      
  app:
    build: ./app
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

# docker-compose -f docker-compose.prod.yml up -d --build 