version: "3.9"

services:
  app:
    build:
      context: ./app
      args:
        - DB_DOCKER_HOST=db
        - DB_PORT=${DB_PORT}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    #    env_file:
    #      - app/.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    restart: always

  db:
    image: postgres:14.4-alpine
    ports:
      - 0.0.0.0:5432:5432
    container_name: db
    networks:
      - djangonetwork
    restart: always

networks:
  djangonetwork:
    driver: bridge